'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin_HubFirmware
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHead As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFirmware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirmware As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFirmwareVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirmwareVersion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSelectFirmware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectFirmware As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlFirmware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFirmware As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnUpdateFirmware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateFirmware As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divFirmwareUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFirmwareUpdate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divFirmwareStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFirmwareStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnRetry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetry As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblCommandSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommandSent As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCheckingforUpdates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCheckingforUpdates As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divProgressBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProgressBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divProgressPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProgressPercent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblHubFirmwareError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHubFirmwareError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnMAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMAC As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnFirmwareDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnFirmwareDesc As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tmrHubFirmware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tmrHubFirmware As Global.System.Web.UI.Timer
End Class
