'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HubReset

	'''<summary>
	'''lblHead control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblHead As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''updProgressBar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents updProgressBar As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''lblFirmware control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblFirmware As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblMacAddress control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMacAddress As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''btnGatewayReboot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnGatewayReboot As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''lblGatewayReboot control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblGatewayReboot As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''divProgressBar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divProgressBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''divProgressPercent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divProgressPercent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''tmrProgressBar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tmrProgressBar As Global.System.Web.UI.Timer
End Class
