'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageRiskLevel
    
    '''<summary>
    '''updRiskLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRiskLevels As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''cboDistributors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDistributors As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgInfo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''btn1stAlarmOpenClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn1stAlarmOpenClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''collapse1stAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collapse1stAlarm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Label74 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label74 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label73 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label73 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink1 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboHighContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboHighContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink25 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label50 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbo1stAlarmHighSilencedValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAlarmHighSilencedValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label106 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label106 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label51 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label52 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink54 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo1stAlarmHighSilencedContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAlarmHighSilencedContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink53 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink2 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo1stAlarmHighNotSilencedContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAlarmHighNotSilencedContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink26 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label75 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label75 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink3 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboMediumContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMediumContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink27 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbo1stAlarmMediumSilencedValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAlarmMediumSilencedValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label59 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label59 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label60 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label60 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink51 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo1stAlarmMediumSilencedContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAlarmMediumSilencedContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink52 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink5 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo1stAlarmMediumNotSilencedContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAlarmMediumNotSilencedContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink28 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label76 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label76 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink4 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboLowContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboLowContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink29 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbo1stAlarmLowSilencedValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAlarmLowSilencedValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label67 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label67 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label68 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label68 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink49 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo1stAlarmLowSilencedContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAlarmLowSilencedContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink50 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink6 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo1stAlarmLowNotSilencedContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo1stAlarmLowNotSilencedContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink30 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''btnSave1stAlarmCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave1stAlarmCondition As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbl1stAlarmUpdateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1stAlarmUpdateStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''btn2ndAlarmOpenClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn2ndAlarmOpenClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''collapse2ndAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collapse2ndAlarm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Label25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label25 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label26 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbo2ndAlarmHighThresholdValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo2ndAlarmHighThresholdValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label62 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label62 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label27 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label28 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink7 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo2ndAlarmHighThresholdYesContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo2ndAlarmHighThresholdYesContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink31 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink8 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo2ndAlarmHighThresholdNoContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo2ndAlarmHighThresholdNoContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink32 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label33 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label34 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbo2ndAlarmMediumThresholdValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo2ndAlarmMediumThresholdValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label35 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label36 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink9 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo2ndAlarmMediumThresholdYesContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo2ndAlarmMediumThresholdYesContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink33 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink10 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo2ndAlarmMediumThresholdNoContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo2ndAlarmMediumThresholdNoContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink34 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label41 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label42 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbo2ndAlarmLowThresholdValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo2ndAlarmLowThresholdValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label43 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label44 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink11 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo2ndAlarmLowThresholdYesContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo2ndAlarmLowThresholdYesContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink35 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink12 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cbo2ndAlarmLowThresholdNoContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo2ndAlarmLowThresholdNoContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink36 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''btnSave2ndAlarmCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave2ndAlarmCondition As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbl2ndAlarmUpdateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl2ndAlarmUpdateStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''btnFaultConditionOpenClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFaultConditionOpenClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''collapseFaultCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collapseFaultCondition As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label15 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label16 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label17 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink13 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboFaultHighContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFaultHighContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink37 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink14 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboFaultMediumContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFaultMediumContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink38 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink15 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboFaultLowContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFaultLowContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink39 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''btnSaveFaultCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveFaultCondition As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFaultConditionUpdateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFaultConditionUpdateStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Image3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''btnLossOfCommsOpenClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLossOfCommsOpenClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''collapseLossOfComms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collapseLossOfComms As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Label11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label14 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label18 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink16 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboLossOfCommsHighContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboLossOfCommsHighContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink40 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink17 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboLossOfCommsMediumContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboLossOfCommsMediumContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink41 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink18 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboLossOfCommsLowContactList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboLossOfCommsLowContactList As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink42 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''btnSaveLossofComms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveLossofComms As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblLossOfCommsUpdateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLossOfCommsUpdateStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Image4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''btnDeteriorationMonitorOpenClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeteriorationMonitorOpenClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''collapseDeteriorationMonitor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents collapseDeteriorationMonitor As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Label70 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label70 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationHighMinutesAlarmEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationHighMinutesAlarmEvents As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label80 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label80 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationHighMinutesValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationHighMinutesValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label81 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label81 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationHighDaysAlarmEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationHighDaysAlarmEvents As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label82 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationHighDaysValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationHighDaysValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label83 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label83 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink19 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboDeteriorationHighMinutesContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationHighMinutesContact As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink43 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink20 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboDeteriorationHighDaysContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationHighDaysContact As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink44 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label108 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label108 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label85 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label85 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationMediumMinutesAlarmEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationMediumMinutesAlarmEvents As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label86 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label86 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationMediumMinutesValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationMediumMinutesValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label87 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label87 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationMediumDaysAlarmEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationMediumDaysAlarmEvents As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label88 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label88 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationMediumDaysValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationMediumDaysValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label89 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label89 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink21 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboDeteriorationMediumMinutesContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationMediumMinutesContact As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink45 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink22 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboDeteriorationMediumDaysContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationMediumDaysContact As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink46 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label107 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label107 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label97 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label97 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationLowMinutesAlarmEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationLowMinutesAlarmEvents As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label98 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label98 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationLowMinutesValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationLowMinutesValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label99 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label99 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationLowDaysAlarmEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationLowDaysAlarmEvents As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label100 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cboDeteriorationLowDaysValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationLowDaysValue As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Label101 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label101 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hyperlink23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink23 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboDeteriorationLowMinutesContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationLowMinutesContact As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink47 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''hyperlink24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink24 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''cboDeteriorationLowDaysContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeteriorationLowDaysContact As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''hyperlink48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlink48 As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''Label109 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label109 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSaveDeteriorationLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveDeteriorationLevels As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblDeteriorationStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeteriorationStatus As Global.System.Web.UI.WebControls.Label
End Class
