'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageSensors
    
    '''<summary>
    '''updAccountandProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updAccountandProperty As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''litAccountHolderText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAccountHolderText As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblAccounHolderValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccounHolderValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litMacAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMacAddressText As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblMacAddressValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMacAddressValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litAccountIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAccountIDText As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblAccountIDValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountIDValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litropertyAddressText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litropertyAddressText As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblPropertyAddressValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPropertyAddressValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEdit As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblGateway control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGateway As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnGatewayOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGatewayOpen As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''updGateways control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updGateways As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''radGateSensors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radGateSensors As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''btnGatewayClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGatewayClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblRegSensor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegSensor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnRegSensorOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegSensorOpen As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''updSensors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updSensors As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''radGridSensors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radGridSensors As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''btnRegSensorClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegSensorClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblUnRegSensor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnRegSensor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnUnRegSensorOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUnRegSensorOpen As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''updUnRegSensors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updUnRegSensors As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''radGridUnregisteredSensors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radGridUnregisteredSensors As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''btnUnRegSensorClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUnRegSensorClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblArchivedSensor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArchivedSensor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnArchivedSensorOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnArchivedSensorOpen As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''updArchivedSensors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updArchivedSensors As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''radGridArchivedSensors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radGridArchivedSensors As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''btnArchivedSensorClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnArchivedSensorClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''timerRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timerRefresh As Global.System.Web.UI.Timer
    
    '''<summary>
    '''litEditPropertyAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEditPropertyAddress As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''txtEditPropertyAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditPropertyAddress1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditPropertyAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditPropertyAddress2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditPropertyAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditPropertyAddress3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditPropertyAddress4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditPropertyAddress4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditPropertyPostCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditPropertyPostCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditAccountAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditAccountAddress1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditAccountAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditAccountAddress2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditAccountAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditAccountAddress3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditAccountAddress4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditAccountAddress4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditAccountPostCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditAccountPostCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkUseAccountAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseAccountAddress As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cboEditPropertyRiskLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEditPropertyRiskLevel As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Button3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUpdateAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateAddress As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdnDeviceSeq1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDeviceSeq1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnPropZone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPropZone1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''litEditDevice1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEditDevice1 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litDeviceTypeLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDeviceTypeLabel1 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblDeviceType1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeviceType1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litDeviceName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDeviceName1 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblGatewayDeviceName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGatewayDeviceName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Literal21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal21 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Literal11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal11 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''txtDeviceLocation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeviceLocation1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Literal5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal5 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''updEditGateway control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updEditGateway As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''cboGatewayZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGatewayZone As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUpdateGateway control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateGateway As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Literal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal3 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Literal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal4 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemove As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdnDeviceSeq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDeviceSeq As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnPropZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPropZone As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''litEditDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEditDevice As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litDeviceTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDeviceTypeLabel As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblDeviceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeviceType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''litDeviceName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litDeviceName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblSensorDeviceName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSensorDeviceName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Literal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''txtDeviceLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeviceLocation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Literal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal2 As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''updEditSensor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updEditSensor As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''cboDeviceZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDeviceZone As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''divColdAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divColdAlarm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkSounder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSounder As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''drpRadTemperature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpRadTemperature As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUpdateSensor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateSensor As Global.System.Web.UI.WebControls.Button
End Class
