'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SwapPanel
    
    '''<summary>
    '''lblAccountID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccountID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AccountID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccountID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOldMACAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOldMACAddress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OldMACAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OldMACAddress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNewMACAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewMACAddress As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtHubMAC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtHubMAC12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHubMAC12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''valHubMAC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC1 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC2 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC3 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC4 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC5 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC6 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC7 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC8 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC9 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC10 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC11 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valHubMAC12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHubMAC12 As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''valMAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valMAC As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''btnSwapPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSwapPanel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ModalSwapGateway control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModalSwapGateway As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''litSwapGWWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSwapGWWarning As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''litSwapGWPrompt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSwapGWPrompt As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''btnSwapGWCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSwapGWCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSwapGWOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSwapGWOK As Global.System.Web.UI.WebControls.Button
End Class
