'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AuditTypeResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.AuditTypeResources", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Access Customer Account.
        '''</summary>
        Friend Shared ReadOnly Property Admin_AccessCustomerAccount() As String
            Get
                Return ResourceManager.GetString("Admin_AccessCustomerAccount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Status Change.
        '''</summary>
        Friend Shared ReadOnly Property Admin_AccountStatus_Change() As String
            Get
                Return ResourceManager.GetString("Admin_AccountStatus_Change", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Details Created.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Account_Details_Created() As String
            Get
                Return ResourceManager.GetString("Admin_Account_Details_Created", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Details Updated.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Account_Details_Updated() As String
            Get
                Return ResourceManager.GetString("Admin_Account_Details_Updated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Login.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Account_Login() As String
            Get
                Return ResourceManager.GetString("Admin_Account_Login", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Logout.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Account_Logout() As String
            Get
                Return ResourceManager.GetString("Admin_Account_Logout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Viewed.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Account_Viewed() As String
            Get
                Return ResourceManager.GetString("Admin_Account_Viewed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Admin User.
        '''</summary>
        Friend Shared ReadOnly Property Admin_AddAdminUser() As String
            Get
                Return ResourceManager.GetString("Admin_AddAdminUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Alert Contact.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Add_Alert_Contact() As String
            Get
                Return ResourceManager.GetString("Admin_Add_Alert_Contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Admin User.
        '''</summary>
        Friend Shared ReadOnly Property Admin_DeleteAdminUser() As String
            Get
                Return ResourceManager.GetString("Admin_DeleteAdminUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Admin User.
        '''</summary>
        Friend Shared ReadOnly Property Admin_EditAdminUser() As String
            Get
                Return ResourceManager.GetString("Admin_EditAdminUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Profile.
        '''</summary>
        Friend Shared ReadOnly Property Admin_EditProfile() As String
            Get
                Return ResourceManager.GetString("Admin_EditProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit Alert Contact.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Edit_Alert_Contact() As String
            Get
                Return ResourceManager.GetString("Admin_Edit_Alert_Contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Firmware Update Failed.
        '''</summary>
        Friend Shared ReadOnly Property Admin_FirmwareUpdate_Failed() As String
            Get
                Return ResourceManager.GetString("Admin_FirmwareUpdate_Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Firmware Update Success.
        '''</summary>
        Friend Shared ReadOnly Property Admin_FirmwareUpdate_Success() As String
            Get
                Return ResourceManager.GetString("Admin_FirmwareUpdate_Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gateway Factory Reset.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Gateway_Factory_Reset() As String
            Get
                Return ResourceManager.GetString("Admin_Gateway_Factory_Reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gateway Factory Reset Success.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Gateway_Factory_Reset_Success() As String
            Get
                Return ResourceManager.GetString("Admin_Gateway_Factory_Reset_Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gateway Removed.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Gateway_Removed() As String
            Get
                Return ResourceManager.GetString("Admin_Gateway_Removed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gateway Swapped.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Gateway_Swapped() As String
            Get
                Return ResourceManager.GetString("Admin_Gateway_Swapped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notes Added.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Notes_Added() As String
            Get
                Return ResourceManager.GetString("Admin_Notes_Added", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notes Deleted.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Notes_Deleted() As String
            Get
                Return ResourceManager.GetString("Admin_Notes_Deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notes Updated.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Notes_Updated() As String
            Get
                Return ResourceManager.GetString("Admin_Notes_Updated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Panel Reset.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Panel_Reset() As String
            Get
                Return ResourceManager.GetString("Admin_Panel_Reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Updated.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Property_Updated() As String
            Get
                Return ResourceManager.GetString("Admin_Property_Updated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Property Viewed.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Property_Viewed() As String
            Get
                Return ResourceManager.GetString("Admin_Property_Viewed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Profile.
        '''</summary>
        Friend Shared ReadOnly Property Admin_SaveProfile() As String
            Get
                Return ResourceManager.GetString("Admin_SaveProfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Alert Contact.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Save_Alert_Contact() As String
            Get
                Return ResourceManager.GetString("Admin_Save_Alert_Contact", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sensor Details Updated.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Sensor_Details_Updated() As String
            Get
                Return ResourceManager.GetString("Admin_Sensor_Details_Updated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sensor Removed.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Sensor_Removed() As String
            Get
                Return ResourceManager.GetString("Admin_Sensor_Removed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Support Request Added.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Support_Requests_Added() As String
            Get
                Return ResourceManager.GetString("Admin_Support_Requests_Added", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Support Request Updated.
        '''</summary>
        Friend Shared ReadOnly Property Admin_Support_Requests_Updated() As String
            Get
                Return ResourceManager.GetString("Admin_Support_Requests_Updated", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
