'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class DevicePropertyResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.DevicePropertyResources", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heat Sensor AC.
        '''</summary>
        Friend Shared ReadOnly Property ACHeatAlarm() As String
            Get
                Return ResourceManager.GetString("ACHeatAlarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/heat-sensor-ac.png.
        '''</summary>
        Friend Shared ReadOnly Property ACHeatAlarmImage() As String
            Get
                Return ResourceManager.GetString("ACHeatAlarmImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Smoke Sensor.
        '''</summary>
        Friend Shared ReadOnly Property ACSmokeAlarm() As String
            Get
                Return ResourceManager.GetString("ACSmokeAlarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/co-sensor-dc.png.
        '''</summary>
        Friend Shared ReadOnly Property ACSmokeAlarmImage() As String
            Get
                Return ResourceManager.GetString("ACSmokeAlarmImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Alarm Control Unit.
        '''</summary>
        Friend Shared ReadOnly Property AlarmControlUnit() As String
            Get
                Return ResourceManager.GetString("AlarmControlUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/alarm-control-unit.png.
        '''</summary>
        Friend Shared ReadOnly Property AlarmControlUnitImage() As String
            Get
                Return ResourceManager.GetString("AlarmControlUnitImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CO Sensor DC.
        '''</summary>
        Friend Shared ReadOnly Property COAlarm() As String
            Get
                Return ResourceManager.GetString("COAlarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/co-sensor-dc.png.
        '''</summary>
        Friend Shared ReadOnly Property COAlarmImage() As String
            Get
                Return ResourceManager.GetString("COAlarmImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cold Sensor.
        '''</summary>
        Friend Shared ReadOnly Property ColdAlarm() As String
            Get
                Return ResourceManager.GetString("ColdAlarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/cold-sensor-dc.png.
        '''</summary>
        Friend Shared ReadOnly Property ColdAlarmImage() As String
            Get
                Return ResourceManager.GetString("ColdAlarmImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heat Sensor DC.
        '''</summary>
        Friend Shared ReadOnly Property HeatAlarm() As String
            Get
                Return ResourceManager.GetString("HeatAlarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/heat-sensor-dc.png.
        '''</summary>
        Friend Shared ReadOnly Property HeatAlarmImage() As String
            Get
                Return ResourceManager.GetString("HeatAlarmImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interface Gateway.
        '''</summary>
        Friend Shared ReadOnly Property InterfaceGateway() As String
            Get
                Return ResourceManager.GetString("InterfaceGateway", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interface Gateway 200.
        '''</summary>
        Friend Shared ReadOnly Property InterfaceGateway200() As String
            Get
                Return ResourceManager.GetString("InterfaceGateway200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/interface-gateway.png.
        '''</summary>
        Friend Shared ReadOnly Property InterfaceGatewayImage() As String
            Get
                Return ResourceManager.GetString("InterfaceGatewayImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/interface-gateway.png.
        '''</summary>
        Friend Shared ReadOnly Property InterfaceGatewayImage200() As String
            Get
                Return ResourceManager.GetString("InterfaceGatewayImage200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Low Frequency Sounder.
        '''</summary>
        Friend Shared ReadOnly Property LowFreqSounder() As String
            Get
                Return ResourceManager.GetString("LowFreqSounder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/low-frequency.png.
        '''</summary>
        Friend Shared ReadOnly Property LowFreqSounderImage() As String
            Get
                Return ResourceManager.GetString("LowFreqSounderImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Strobe &amp; Vibrating Pad.
        '''</summary>
        Friend Shared ReadOnly Property PadStrobe() As String
            Get
                Return ResourceManager.GetString("PadStrobe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/strobe-pad.png.
        '''</summary>
        Friend Shared ReadOnly Property PadStrobeImage() As String
            Get
                Return ResourceManager.GetString("PadStrobeImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Smoke Sensor.
        '''</summary>
        Friend Shared ReadOnly Property SmokeAlarm() As String
            Get
                Return ResourceManager.GetString("SmokeAlarm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /common/img/ZoneDevices/cold-sensor-dc.png.
        '''</summary>
        Friend Shared ReadOnly Property SmokeAlarmImage() As String
            Get
                Return ResourceManager.GetString("SmokeAlarmImage", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
