'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class MenuResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.MenuResources", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Admin/AccountSearch.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MenuAccountsPage() As String
            Get
                Return ResourceManager.GetString("MenuAccountsPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend Shared ReadOnly Property MenuAccountsPermittedCompanies() As String
            Get
                Return ResourceManager.GetString("MenuAccountsPermittedCompanies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AdminUser.
        '''</summary>
        Friend Shared ReadOnly Property MenuAccountsPermittedRoles() As String
            Get
                Return ResourceManager.GetString("MenuAccountsPermittedRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Enquiry.
        '''</summary>
        Friend Shared ReadOnly Property MenuAccountsText() As String
            Get
                Return ResourceManager.GetString("MenuAccountsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Admin/UserAccountSearch.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MenuAdministrationPage() As String
            Get
                Return ResourceManager.GetString("MenuAdministrationPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend Shared ReadOnly Property MenuAdministrationPermittedCompanies() As String
            Get
                Return ResourceManager.GetString("MenuAdministrationPermittedCompanies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AdminUser.
        '''</summary>
        Friend Shared ReadOnly Property MenuAdministrationPermittedRoles() As String
            Get
                Return ResourceManager.GetString("MenuAdministrationPermittedRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administration.
        '''</summary>
        Friend Shared ReadOnly Property MenuAdministrationText() As String
            Get
                Return ResourceManager.GetString("MenuAdministrationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Admin/EventLog.aspx?T=1.
        '''</summary>
        Friend Shared ReadOnly Property MenuEventsPage() As String
            Get
                Return ResourceManager.GetString("MenuEventsPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend Shared ReadOnly Property MenuEventsPermittedCompanies() As String
            Get
                Return ResourceManager.GetString("MenuEventsPermittedCompanies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AdminUser.
        '''</summary>
        Friend Shared ReadOnly Property MenuEventsPermittedRoles() As String
            Get
                Return ResourceManager.GetString("MenuEventsPermittedRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Event Log.
        '''</summary>
        Friend Shared ReadOnly Property MenuEventsText() As String
            Get
                Return ResourceManager.GetString("MenuEventsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Admin/LoginSearch.aspx.
        '''</summary>
        Friend Shared ReadOnly Property MenuLoginsPage() As String
            Get
                Return ResourceManager.GetString("MenuLoginsPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend Shared ReadOnly Property MenuLoginsPermittedCompanies() As String
            Get
                Return ResourceManager.GetString("MenuLoginsPermittedCompanies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SuperAdmin,SupportAdmin.
        '''</summary>
        Friend Shared ReadOnly Property MenuLoginsPermittedRoles() As String
            Get
                Return ResourceManager.GetString("MenuLoginsPermittedRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manage Users.
        '''</summary>
        Friend Shared ReadOnly Property MenuLoginsText() As String
            Get
                Return ResourceManager.GetString("MenuLoginsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Admin/ManageRiskLevel.aspx?T=1.
        '''</summary>
        Friend Shared ReadOnly Property MenuRisksPage() As String
            Get
                Return ResourceManager.GetString("MenuRisksPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conditional.
        '''</summary>
        Friend Shared ReadOnly Property MenuRisksPermittedCompanies() As String
            Get
                Return ResourceManager.GetString("MenuRisksPermittedCompanies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AdminUser.
        '''</summary>
        Friend Shared ReadOnly Property MenuRisksPermittedRoles() As String
            Get
                Return ResourceManager.GetString("MenuRisksPermittedRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manage Risk Level.
        '''</summary>
        Friend Shared ReadOnly Property MenuRisksText() As String
            Get
                Return ResourceManager.GetString("MenuRisksText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ~/Admin/SupportSearch.aspx?T=1.
        '''</summary>
        Friend Shared ReadOnly Property MenuSupportPage() As String
            Get
                Return ResourceManager.GetString("MenuSupportPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend Shared ReadOnly Property MenuSupportPermittedCompanies() As String
            Get
                Return ResourceManager.GetString("MenuSupportPermittedCompanies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AdminUser.
        '''</summary>
        Friend Shared ReadOnly Property MenuSupportPermittedRoles() As String
            Get
                Return ResourceManager.GetString("MenuSupportPermittedRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Support Tickets.
        '''</summary>
        Friend Shared ReadOnly Property MenuSupportText() As String
            Get
                Return ResourceManager.GetString("MenuSupportText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accounts,Support,Administration,Events,Logins,Risks.
        '''</summary>
        Friend Shared ReadOnly Property TopMenuItems() As String
            Get
                Return ResourceManager.GetString("TopMenuItems", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
