'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ValidationCtlResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.ValidationCtlResources", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must supply the first line of the address.&amp;nbsp;.
        '''</summary>
        Friend Shared ReadOnly Property Address1RequiredMsg() As String
            Get
                Return ResourceManager.GetString("Address1RequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You must enter the date on which to perform the change..
        '''</summary>
        Friend Shared ReadOnly Property ChangeDateRequiredMsg() As String
            Get
                Return ResourceManager.GetString("ChangeDateRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company Name required..
        '''</summary>
        Friend Shared ReadOnly Property CoNameRequiredMsg() As String
            Get
                Return ResourceManager.GetString("CoNameRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Country must be selected..
        '''</summary>
        Friend Shared ReadOnly Property CountryRequiredMsg() As String
            Get
                Return ResourceManager.GetString("CountryRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Distributor must be selected..
        '''</summary>
        Friend Shared ReadOnly Property DistributorRequiredMsg() As String
            Get
                Return ResourceManager.GetString("DistributorRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^[a-zA-Z][\w\.-]*[a-zA-Z0-9]@[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]$.
        '''</summary>
        Friend Shared ReadOnly Property EmailFormatExpression() As String
            Get
                Return ResourceManager.GetString("EmailFormatExpression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entered value is not in the correct format.&amp;nbsp;.
        '''</summary>
        Friend Shared ReadOnly Property EmailFormatMsg() As String
            Get
                Return ResourceManager.GetString("EmailFormatMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email Address required.&amp;nbsp;.
        '''</summary>
        Friend Shared ReadOnly Property EmailRequiredMsg() As String
            Get
                Return ResourceManager.GetString("EmailRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Name required.&amp;nbsp;.
        '''</summary>
        Friend Shared ReadOnly Property FirstNameRequiredMsg() As String
            Get
                Return ResourceManager.GetString("FirstNameRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^0([\d]{9,})$.
        '''</summary>
        Friend Shared ReadOnly Property FixedTelephoneFormatExpression() As String
            Get
                Return ResourceManager.GetString("FixedTelephoneFormatExpression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UK Phone numbers must start with 0, and be at least 9 digits long..
        '''</summary>
        Friend Shared ReadOnly Property FixedTelephoneFormatMsg() As String
            Get
                Return ResourceManager.GetString("FixedTelephoneFormatMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Name required.&amp;nbsp;.
        '''</summary>
        Friend Shared ReadOnly Property LastNameRequiredMsg() As String
            Get
                Return ResourceManager.GetString("LastNameRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile Number is required..
        '''</summary>
        Friend Shared ReadOnly Property MobileNumberReq() As String
            Get
                Return ResourceManager.GetString("MobileNumberReq", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^07([\d]{3})[(\D\s)]?[\d]{3}[(\D\s)]?[\d]{3}$.
        '''</summary>
        Friend Shared ReadOnly Property MobileTelephoneFormatExpression() As String
            Get
                Return ResourceManager.GetString("MobileTelephoneFormatExpression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UK Phone numbers must start with 07, can only contain numbers and must be 11 digits..
        '''</summary>
        Friend Shared ReadOnly Property MobileTelephoneFormatMsg() As String
            Get
                Return ResourceManager.GetString("MobileTelephoneFormatMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^\D+\d[\s]*[\D\d]*$.
        '''</summary>
        Friend Shared ReadOnly Property PostcodeformatExpression() As String
            Get
                Return ResourceManager.GetString("PostcodeformatExpression", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Postcode must start with a letter and contain at least one number.
        '''</summary>
        Friend Shared ReadOnly Property PostcodeFormatMsg() As String
            Get
                Return ResourceManager.GetString("PostcodeFormatMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Post Code required.&amp;nbsp;.
        '''</summary>
        Friend Shared ReadOnly Property PostCodeRequiredMsg() As String
            Get
                Return ResourceManager.GetString("PostCodeRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Service Provider must be selected..
        '''</summary>
        Friend Shared ReadOnly Property ProviderRequiredMsg() As String
            Get
                Return ResourceManager.GetString("ProviderRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State/County required.&amp;nbsp;.
        '''</summary>
        Friend Shared ReadOnly Property StateTerritoryRequiredMsg() As String
            Get
                Return ResourceManager.GetString("StateTerritoryRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Time Zone must be selected..
        '''</summary>
        Friend Shared ReadOnly Property TimeZoneRequiredMsg() As String
            Get
                Return ResourceManager.GetString("TimeZoneRequiredMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The &apos;To&apos; date must be later than the &apos;From&apos; date..
        '''</summary>
        Friend Shared ReadOnly Property ToFromMismatchMsg() As String
            Get
                Return ResourceManager.GetString("ToFromMismatchMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Town/City required.&amp;nbsp;.
        '''</summary>
        Friend Shared ReadOnly Property TownCityRequiredMsg() As String
            Get
                Return ResourceManager.GetString("TownCityRequiredMsg", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
